flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- texmath-0.12.0.2
- haddock-library-1.9.0
- skylighting-0.8.5
- skylighting-core-0.8.5
- regex-pcre-builtin-0.95.1.2.8.43
- regex-base-0.94.0.0
- doclayout-0.3
- emojis-0.1
- hslua-1.1.0
- jira-wiki-markup-1.3.2
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
- pandoc-types-1.21
- git: 'https://github.com/jgm/pandoc'
  commit: 9672ff827194ddf5565351b2fdde942c03942b2d

ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-14.6
